### ISSUE TITLE
Windows  64 位系统 报错 

### ISSUE THREAD

**Issue by BadDeveloper2022** [hazen1314/dy233_unidbg_sign#1]
File opened 'stdin' with oflags=0x0 from null
File opened 'stdout' with oflags=0x1 from null
File opened 'stderr' with oflags=0x1 from null
Exception in thread "main" java.lang.IllegalStateException: load library failed: metasec_ml
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:237)
	at com.ss.android.ugc.aweme.Sign6.<init>(Sign6.java:45)
	at com.ss.android.ugc.aweme.Sign6.main(Sign6.java:134)

都是按照你说的来配置和复制的。
代码也没有更改，去掉了checkVersion

**Comment by BadDeveloper2022** [comment]
libs 文件夹 只有 arm64-v8a  ，虚拟机是32 ，改成64 找到so库，但是后面出问题

**Comment by hazen1314** [comment]
> 

请问可以提供下你的 apk 文件吗？

**Comment by sen19982016** [comment]
MacOS 13.0 按照步骤配置，也出现了同样的错误，apk是从ReadMe文件中提供的豌豆荚链接下载的。

**Comment by oyo775881** [comment]
真的是一样的错···不懂什么原因··

**Comment by sen19982016** [comment]
> unidbg-android/src/test/resources/dy233/dy233.apk
你好大哥，按照你说的把这儿改成绝对路径还是报和以前一样的错误。但是你另外一个python版的项目运行起来是没什么问题的。
